import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Search, ShieldCheck, Building2, MapPin, Home, TrendingUp, UserCheck, CalendarDays, Heart, Menu, X, LayoutDashboard, CheckCircle2, IndianRupee, Filter, Upload, Users, BarChart3, Lock, ArrowRight, Phone, MessageCircle } from 'lucide-react';
import './styles.css';

const societies = [
  { id: 1, slug: 'dlf-park-place', name: 'DLF Park Place', city: 'Gurgaon', locality: 'Golf Course Road', rent: '₹78k–1.4L', active: 18, verified: true, image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=1200&auto=format&fit=crop', bhk: '3/4 BHK', avg2: '₹68k', avg3: '₹92k' },
  { id: 2, slug: 'm3m-golf-estate', name: 'M3M Golf Estate', city: 'Gurgaon', locality: 'Sector 65', rent: '₹95k–2.4L', active: 11, verified: true, image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?q=80&w=1200&auto=format&fit=crop', bhk: '3/4 BHK', avg2: '₹82k', avg3: '₹1.15L' },
  { id: 3, slug: 'prestige-shantiniketan', name: 'Prestige Shantiniketan', city: 'Bangalore', locality: 'Whitefield', rent: '₹48k–95k', active: 27, verified: true, image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop', bhk: '2/3 BHK', avg2: '₹52k', avg3: '₹76k' },
  { id: 4, slug: 'brigade-gateway', name: 'Brigade Gateway', city: 'Bangalore', locality: 'Rajajinagar', rent: '₹55k–1.2L', active: 14, verified: true, image: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?q=80&w=1200&auto=format&fit=crop', bhk: '2/3/4 BHK', avg2: '₹58k', avg3: '₹84k' },
  { id: 5, slug: 'dlf-the-crest', name: 'DLF The Crest', city: 'Gurgaon', locality: 'DLF Phase 5', rent: '₹1.2L–3L', active: 9, verified: true, image: 'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?q=80&w=1200&auto=format&fit=crop', bhk: '3/4 BHK', avg2: '₹1L', avg3: '₹1.55L' },
  { id: 6, slug: 'sobha-city', name: 'Sobha City', city: 'Bangalore', locality: 'Thanisandra', rent: '₹42k–88k', active: 21, verified: true, image: 'https://images.unsplash.com/photo-1600566752355-35792bedcfea?q=80&w=1200&auto=format&fit=crop', bhk: '2/3 BHK', avg2: '₹44k', avg3: '₹67k' }
];

const listings = [
  { id: 101, slug: 'dlf-park-place-3bhk', society: societies[0], title: '3 BHK high-floor apartment', rent: '₹92,000', deposit: '2 months', maintenance: 'Included', bhk: '3 BHK', area: '1,985 sq.ft', furnishing: 'Semi-furnished', available: 'Immediate', tenants: 'Family preferred', verified: true, featured: true, image: societies[0].image },
  { id: 102, slug: 'prestige-shantiniketan-2bhk', society: societies[2], title: '2 BHK near tech parks', rent: '₹54,000', deposit: '₹1.5L', maintenance: '₹7,500', bhk: '2 BHK', area: '1,420 sq.ft', furnishing: 'Furnished', available: 'From 1 June', tenants: 'Family/Bachelors', verified: true, featured: false, image: societies[2].image },
  { id: 103, slug: 'm3m-golf-estate-4bhk', society: societies[1], title: '4 BHK golf-facing residence', rent: '₹1,85,000', deposit: '2 months', maintenance: 'Extra', bhk: '4 BHK', area: '3,200 sq.ft', furnishing: 'Unfurnished', available: 'Immediate', tenants: 'Family only', verified: true, featured: true, image: societies[1].image },
  { id: 104, slug: 'sobha-city-3bhk', society: societies[5], title: '3 BHK with clubhouse access', rent: '₹68,000', deposit: '₹2L', maintenance: 'Included', bhk: '3 BHK', area: '1,760 sq.ft', furnishing: 'Semi-furnished', available: 'From 15 June', tenants: 'Family preferred', verified: true, featured: false, image: societies[5].image },
  { id: 105, slug: 'brigade-gateway-3bhk', society: societies[3], title: '3 BHK premium tower apartment', rent: '₹86,000', deposit: '₹2.5L', maintenance: 'Included', bhk: '3 BHK', area: '1,890 sq.ft', furnishing: 'Furnished', available: 'Immediate', tenants: 'Family', verified: true, featured: false, image: societies[3].image },
  { id: 106, slug: 'dlf-crest-4bhk', society: societies[4], title: '4 BHK luxury residence', rent: '₹2,45,000', deposit: '3 months', maintenance: 'Extra', bhk: '4 BHK', area: '3,950 sq.ft', furnishing: 'Semi-furnished', available: 'From 5 June', tenants: 'Family only', verified: true, featured: true, image: societies[4].image }
];

function Badge({ children, tone = 'green' }) { return <span className={`badge ${tone}`}>{children}</span>; }
function Button({ children, variant='primary', onClick }) { return <button onClick={onClick} className={`btn ${variant}`}>{children}</button>; }
function Header({ route, setRoute }) {
  const [open, setOpen] = useState(false);
  const nav = [['Rentals','search'],['Societies','society'],['Rent Trends','trends'],['Guides','guides']];
  return <header className="header"><div className="container nav"><button className="logo" onClick={()=>setRoute('home')}><span>SF</span> SocietyFlats</button><nav className="desktop-nav">{nav.map(([n,r])=><button key={r} className={route===r?'active':''} onClick={()=>setRoute(r)}>{n}</button>)}<button onClick={()=>setRoute('post')} className="nav-cta">List Property</button><button onClick={()=>setRoute('dashboard')}>Login</button></nav><button className="mobile-menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div>{open&&<div className="mobile-drawer">{nav.map(([n,r])=><button key={r} onClick={()=>{setRoute(r);setOpen(false)}}>{n}</button>)}<button onClick={()=>{setRoute('post');setOpen(false)}}>List Property</button><button onClick={()=>{setRoute('dashboard');setOpen(false)}}>Login</button></div>}</header>
}
function Hero({ setRoute }) { return <section className="hero"><div className="container hero-grid"><div><Badge tone="gold">Verified Society Rental Network</Badge><h1>Verified society flats in Gurgaon & Bangalore</h1><p className="hero-copy">Search premium rentals by society, locality, budget and move-in date — without fake listings or rental chaos.</p><div className="search-panel"><select><option>Gurgaon</option><option>Bangalore</option></select><div className="search-input"><Search size={18}/><input placeholder="Search society, locality or landmark" /></div><select><option>Any BHK</option><option>2 BHK</option><option>3 BHK</option><option>4 BHK</option></select><select><option>Budget</option><option>Under ₹50k</option><option>₹50k–₹1L</option><option>₹1L+</option></select><Button onClick={()=>setRoute('search')}>Search</Button></div><div className="chips">{['DLF Park Place','Whitefield','M3M Golf Estate','HSR Layout'].map(x=><button key={x} onClick={()=>setRoute('search')}>{x}</button>)}</div><div className="trustbar"><span><ShieldCheck/> Verified listings</span><span><UserCheck/> Owner checked</span><span><CalendarDays/> Visit-ready homes</span></div></div><div className="hero-card"><img src="https://images.unsplash.com/photo-1600607687644-c7171b42498b?q=80&w=1200&auto=format&fit=crop"/><div className="floating-stat"><strong>500+</strong><span>societies mapped for launch</span></div></div></div></section> }
function SocietyCard({ s, setRoute }) { return <article className="society-card" onClick={()=>setRoute('society')}><img src={s.image}/><div><div className="row"><Badge>Verified</Badge><span>{s.active} rentals</span></div><h3>{s.name}</h3><p><MapPin size={15}/> {s.locality}, {s.city}</p><div className="rent-row"><strong>{s.rent}</strong><span>{s.bhk}</span></div></div></article> }
function PropertyCard({ l, setRoute }) { return <article className="property-card"><div className="image-wrap"><img src={l.image}/><div className="overlay-badges">{l.featured&&<Badge tone="gold">Featured</Badge>}<Badge>Verified</Badge></div></div><div className="property-body"><div className="price"><strong>{l.rent}</strong><span>{l.bhk}</span></div><h3>{l.society.name}</h3><p>{l.title}</p><div className="meta"><span>{l.society.locality}</span><span>{l.furnishing}</span><span>{l.available}</span></div><Button variant="secondary" onClick={()=>setRoute('property')}>View Details</Button></div></article> }
function HomePage({ setRoute }) { return <><Hero setRoute={setRoute}/><section className="section"><div className="container section-head"><div><Badge tone="gold">Society-first discovery</Badge><h2>Featured societies</h2></div><button onClick={()=>setRoute('search')}>View all <ArrowRight size={16}/></button></div><div className="container grid societies">{societies.map(s=><SocietyCard key={s.id} s={s} setRoute={setRoute}/>)}</div></section><section className="section warm"><div className="container section-head"><div><Badge>Verified rentals</Badge><h2>Latest visit-ready homes</h2></div></div><div className="container grid properties">{listings.slice(0,3).map(l=><PropertyCard key={l.id} l={l} setRoute={setRoute}/>)}</div></section><section className="section"><div className="container intelligence"><div><Badge tone="gold">Rental intelligence</Badge><h2>Built as a data product, not a classified board</h2><p>Track average rents, active inventory, society demand and tenant behaviour across Gurgaon and Bangalore.</p></div><div className="stats-grid"><div><TrendingUp/><strong>₹92k</strong><span>Avg 3BHK: Golf Course Road</span></div><div><Building2/><strong>27</strong><span>Active rentals: Whitefield sample</span></div><div><ShieldCheck/><strong>91%</strong><span>Verified inventory target</span></div><div><Users/><strong>4</strong><span>User roles: tenant, owner, broker, admin</span></div></div></div></section><section className="section cta"><div className="container cta-box"><h2>Own a flat in a premium society?</h2><p>List it with verification and reach serious tenants faster.</p><Button variant="premium" onClick={()=>setRoute('post')}>List Your Property</Button></div></section></> }
function SearchPage({ setRoute }) { const [city,setCity]=useState('All'); const filtered=useMemo(()=>city==='All'?listings:listings.filter(l=>l.society.city===city),[city]); return <main className="page"><div className="container"><div className="page-title"><Badge>Search</Badge><h1>{filtered.length} verified rentals</h1><p>Society-first rental discovery for Gurgaon and Bangalore.</p></div><div className="search-layout"><aside className="filters"><h3><Filter size={18}/> Filters</h3><label>City<select value={city} onChange={e=>setCity(e.target.value)}><option>All</option><option>Gurgaon</option><option>Bangalore</option></select></label><label>BHK<select><option>Any</option><option>2 BHK</option><option>3 BHK</option><option>4 BHK</option></select></label><label>Budget<select><option>Any</option><option>Under ₹50k</option><option>₹50k–₹1L</option><option>₹1L+</option></select></label><label><input type="checkbox"/> Verified only</label><Button>Save Alert</Button></aside><section className="results">{filtered.map(l=><PropertyCard key={l.id} l={l} setRoute={setRoute}/>)}</section></div></div></main> }
function PropertyPage() { const l=listings[0]; return <main className="page"><div className="container detail"><div className="gallery"><img src={l.image}/><img src={societies[1].image}/><img src={societies[2].image}/></div><div className="detail-grid"><section><Badge>Verified Property</Badge><h1>{l.bhk} in {l.society.name}</h1><p className="muted"><MapPin size={16}/> {l.society.locality}, {l.society.city}</p><div className="spec-grid">{[[l.rent,'Monthly Rent'],[l.deposit,'Deposit'],[l.area,'Area'],[l.furnishing,'Furnishing'],[l.available,'Available'],[l.tenants,'Tenant Preference']].map(([a,b])=><div><strong>{a}</strong><span>{b}</span></div>)}</div><h2>Property details</h2><p>High-quality society apartment with power backup, reserved parking, clubhouse access and verified availability. Final inspection and visit confirmation managed by SocietyFlats operations.</p><h2>Society information</h2><p>{l.society.name} is one of the premium residential societies in {l.society.locality}, known for strong maintenance, security and tenant demand.</p></section><aside className="lead-card"><h3>Schedule a visit</h3><input placeholder="Your name"/><input placeholder="Phone number"/><textarea placeholder="I want to visit this property"/><Button><Phone size={16}/> Request Callback</Button><Button variant="secondary"><MessageCircle size={16}/> WhatsApp</Button></aside></div></div></main> }
function SocietyPage({ setRoute }) { const s=societies[0]; return <main className="page"><section className="society-hero"><div className="container"><img src={s.image}/><div><Badge>Verified Society</Badge><h1>{s.name}</h1><p>{s.locality}, {s.city}</p></div></div></section><section className="section"><div className="container society-detail-grid"><div><h2>Premium society rental intelligence</h2><p>{s.name} is a high-demand gated residential society with verified rental inventory, strong family demand and premium amenities.</p><div className="stats-grid compact"><div><strong>{s.avg2}</strong><span>Avg 2BHK rent</span></div><div><strong>{s.avg3}</strong><span>Avg 3BHK rent</span></div><div><strong>{s.active}</strong><span>Active rentals</span></div><div><strong>Family</strong><span>Popular tenant type</span></div></div><h2>Available rentals</h2><div className="results inline">{listings.filter(l=>l.society.id===s.id).map(l=><PropertyCard key={l.id} l={l} setRoute={setRoute}/>)}</div></div><aside className="amenity-box"><h3>Amenities</h3>{['Clubhouse','Gym','Pool','Power backup','Security','Kids play area','Parking','Landscaped greens'].map(a=><span key={a}><CheckCircle2 size={16}/> {a}</span>)}</aside></div></section></main> }
function PostProperty() { return <main className="page"><div className="container narrow"><div className="page-title"><Badge tone="gold">Owner inventory</Badge><h1>List your society flat</h1><p>Submit your rental. Admin verification workflow will approve it before publishing.</p></div><form className="form-card"><div className="two"><input placeholder="Owner name"/><input placeholder="Phone number"/></div><div className="two"><select><option>Gurgaon</option><option>Bangalore</option></select><input placeholder="Society name"/></div><div className="two"><select><option>2 BHK</option><option>3 BHK</option><option>4 BHK</option></select><input placeholder="Monthly rent"/></div><textarea placeholder="Property details"/><div className="upload"><Upload/> Upload images placeholder</div><Button>Submit for Verification</Button></form></div></main> }
function Dashboard() { return <main className="dashboard"><aside><h2>SocietyFlats</h2><button><LayoutDashboard/> Overview</button><button><Heart/> Saved</button><button><CalendarDays/> Visits</button><button><Search/> Alerts</button></aside><section><h1>Tenant Dashboard</h1><div className="stats-grid"><div><strong>6</strong><span>Saved properties</span></div><div><strong>2</strong><span>Visits scheduled</span></div><div><strong>3</strong><span>Search alerts</span></div><div><strong>12</strong><span>New matches</span></div></div><div className="table"><h3>Recent activity</h3><p>Visit requested for DLF Park Place 3 BHK.</p><p>New matching rental found in Whitefield.</p></div></section></main> }
function Admin() { return <main className="dashboard admin"><aside><h2>Admin</h2><button><BarChart3/> Dashboard</button><button><Home/> Listings</button><button><Building2/> Societies</button><button><Users/> Leads</button><button><Lock/> Verification</button></aside><section><h1>Admin Control Center</h1><div className="stats-grid"><div><strong>42</strong><span>New leads today</span></div><div><strong>18</strong><span>Pending listings</span></div><div><strong>9</strong><span>Verifications</span></div><div><strong>₹1.8L</strong><span>MRR target</span></div></div><div className="table"><h3>Lead pipeline</h3>{['New lead — DLF Park Place','Visit scheduled — Prestige Shantiniketan','Verification pending — M3M Golf Estate'].map(x=><p key={x}>{x}</p>)}</div></section></main> }
function Footer({ setRoute }) { return <footer><div className="container footer-grid"><div><h2>SocietyFlats</h2><p>Verified society rentals in Gurgaon and Bangalore.</p></div><div><h4>Explore</h4><button onClick={()=>setRoute('search')}>Rentals</button><button onClick={()=>setRoute('society')}>Societies</button><button>Rent Trends</button></div><div><h4>Company</h4><button>About</button><button>Contact</button><button>Careers</button></div><div><h4>Legal</h4><button>Privacy</button><button>Terms</button><button>Sitemap</button></div></div></footer> }
function App(){ const [route,setRoute]=useState('home'); const map={home:<HomePage setRoute={setRoute}/>,search:<SearchPage setRoute={setRoute}/>,property:<PropertyPage/>,society:<SocietyPage setRoute={setRoute}/>,post:<PostProperty/>,dashboard:<Dashboard/>,admin:<Admin/>,trends:<SearchPage setRoute={setRoute}/>,guides:<HomePage setRoute={setRoute}/>}; const isDash=route==='dashboard'||route==='admin'; return <>{!isDash&&<Header route={route} setRoute={setRoute}/>} {map[route]||map.home} {!isDash&&<Footer setRoute={setRoute}/>}</> }

createRoot(document.getElementById('root')).render(<App/>);
