import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import {
  Search, ShieldCheck, Building2, MapPin, TrendingUp, UserCheck, CalendarDays,
  Menu, X, LayoutDashboard, CheckCircle2, Filter, Upload, Users, BarChart3,
  ArrowRight, Phone, MessageCircle, Home, Heart, IndianRupee, Star, Navigation,
  BriefcaseBusiness, Train, PawPrint, Sparkles, School, Hospital, Clock3, Eye
} from 'lucide-react';
import './styles.css';

const societies = [
  { id: 1, slug: 'dlf-park-place', name: 'DLF Park Place', city: 'Gurgaon', locality: 'Golf Course Road', rent: '₹78k–1.4L', active: 18, verified: true, image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=1600&auto=format&fit=crop', bhk: '3/4 BHK', avg2: '₹68k', avg3: '₹92k', demand: 94 },
  { id: 2, slug: 'm3m-golf-estate', name: 'M3M Golf Estate', city: 'Gurgaon', locality: 'Sector 65', rent: '₹95k–2.4L', active: 11, verified: true, image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?q=80&w=1600&auto=format&fit=crop', bhk: '3/4 BHK', avg2: '₹82k', avg3: '₹1.15L', demand: 91 },
  { id: 3, slug: 'prestige-shantiniketan', name: 'Prestige Shantiniketan', city: 'Bangalore', locality: 'Whitefield', rent: '₹48k–95k', active: 27, verified: true, image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1600&auto=format&fit=crop', bhk: '2/3 BHK', avg2: '₹52k', avg3: '₹76k', demand: 88 },
  { id: 4, slug: 'brigade-gateway', name: 'Brigade Gateway', city: 'Bangalore', locality: 'Rajajinagar', rent: '₹55k–1.2L', active: 14, verified: true, image: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?q=80&w=1600&auto=format&fit=crop', bhk: '2/3/4 BHK', avg2: '₹58k', avg3: '₹84k', demand: 86 },
  { id: 5, slug: 'dlf-the-crest', name: 'DLF The Crest', city: 'Gurgaon', locality: 'DLF Phase 5', rent: '₹1.2L–3L', active: 9, verified: true, image: 'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?q=80&w=1600&auto=format&fit=crop', bhk: '3/4 BHK', avg2: '₹1L', avg3: '₹1.55L', demand: 93 },
  { id: 6, slug: 'sobha-city', name: 'Sobha City', city: 'Bangalore', locality: 'Thanisandra', rent: '₹42k–88k', active: 21, verified: true, image: 'https://images.unsplash.com/photo-1600566752355-35792bedcfea?q=80&w=1600&auto=format&fit=crop', bhk: '2/3 BHK', avg2: '₹44k', avg3: '₹67k', demand: 82 }
];

const listings = [
  { id: 101, slug: 'dlf-park-place-3bhk', society: societies[0], title: 'High-floor apartment with skyline views', rent: '₹92,000', deposit: '2 months', maintenance: 'Included', bhk: '3 BHK', area: '1,985 sq.ft', furnishing: 'Semi-furnished', available: 'Immediate', tenants: 'Family preferred', verified: true, featured: true, image: societies[0].image },
  { id: 102, slug: 'prestige-shantiniketan-2bhk', society: societies[2], title: 'Move-in ready home near tech parks', rent: '₹54,000', deposit: '₹1.5L', maintenance: '₹7,500', bhk: '2 BHK', area: '1,420 sq.ft', furnishing: 'Furnished', available: 'From 1 June', tenants: 'Family/Bachelors', verified: true, featured: false, image: societies[2].image },
  { id: 103, slug: 'm3m-golf-estate-4bhk', society: societies[1], title: 'Golf-facing luxury residence', rent: '₹1,85,000', deposit: '2 months', maintenance: 'Extra', bhk: '4 BHK', area: '3,200 sq.ft', furnishing: 'Unfurnished', available: 'Immediate', tenants: 'Family only', verified: true, featured: true, image: societies[1].image },
  { id: 104, slug: 'sobha-city-3bhk', society: societies[5], title: 'Clubhouse-facing family apartment', rent: '₹68,000', deposit: '₹2L', maintenance: 'Included', bhk: '3 BHK', area: '1,760 sq.ft', furnishing: 'Semi-furnished', available: 'From 15 June', tenants: 'Family preferred', verified: true, featured: false, image: societies[5].image },
  { id: 105, slug: 'brigade-gateway-3bhk', society: societies[3], title: 'Premium tower apartment', rent: '₹86,000', deposit: '₹2.5L', maintenance: 'Included', bhk: '3 BHK', area: '1,890 sq.ft', furnishing: 'Furnished', available: 'Immediate', tenants: 'Family', verified: true, featured: false, image: societies[3].image },
  { id: 106, slug: 'dlf-crest-4bhk', society: societies[4], title: 'Private luxury residence', rent: '₹2,45,000', deposit: '3 months', maintenance: 'Extra', bhk: '4 BHK', area: '3,950 sq.ft', furnishing: 'Semi-furnished', available: 'From 5 June', tenants: 'Family only', verified: true, featured: true, image: societies[4].image }
];

function Badge({ children, tone = 'green' }) { return <span className={`badge ${tone}`}>{children}</span>; }
function Button({ children, variant='primary', onClick }) { return <button onClick={onClick} className={`btn ${variant}`}>{children}</button>; }

function Header({ route, setRoute }) {
  const [open, setOpen] = useState(false);
  const nav = [['Rentals','search'],['Societies','society'],['Rent Trends','trends'],['Guides','guides']];
  return <header className="header"><div className="container nav"><button className="logo" onClick={()=>setRoute('home')}><span>SF</span><b>SocietyFlats</b></button><nav className="desktop-nav">{nav.map(([n,r])=><button key={r} className={route===r?'active':''} onClick={()=>setRoute(r)}>{n}</button>)}<button onClick={()=>setRoute('post')} className="nav-cta">List Property</button><button onClick={()=>setRoute('dashboard')}>Login</button></nav><button className="mobile-menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div>{open&&<div className="mobile-drawer">{nav.map(([n,r])=><button key={r} onClick={()=>{setRoute(r);setOpen(false)}}>{n}</button>)}<button onClick={()=>{setRoute('post');setOpen(false)}}>List Property</button><button onClick={()=>{setRoute('dashboard');setOpen(false)}}>Login</button></div>}</header>
}

function Hero({ setRoute }) {
  return <section className="hero-v3"><div className="hero-photo-bg"/><div className="container hero-v3-grid"><div className="hero-copy"><Badge tone="gold">Verified Society Rental Network</Badge><h1>Find verified homes inside India’s most trusted societies</h1><p>Search premium rentals across Gurgaon and Bangalore. Verified owners, verified inventory and faster move-ins.</p><div className="hero-search"><div className="hero-search-main"><Search size={22}/><input placeholder="Search society, locality or landmark" /></div><div className="hero-search-filters"><select><option>Gurgaon</option><option>Bangalore</option></select><select><option>Any BHK</option><option>2 BHK</option><option>3 BHK</option><option>4 BHK</option></select><select><option>Budget</option><option>Under ₹50k</option><option>₹50k–₹1L</option><option>₹1L+</option></select><Button onClick={()=>setRoute('search')}>Search verified homes</Button></div><div className="chips">{['DLF Park Place','Prestige Shantiniketan','Golf Course Road','Whitefield'].map(x=><button key={x} onClick={()=>setRoute('search')}>{x}</button>)}</div></div></div><div className="hero-visual"><img src="https://images.unsplash.com/photo-1600607687644-c7171b42498b?q=80&w=1800&auto=format&fit=crop"/><div className="hero-visual-card"><strong>800+</strong><span>premium societies mapped across Gurgaon & Bangalore</span></div><div className="hero-visual-chip">Visit-ready homes</div></div></div></section>
}

function TrustMetrics() {
  const items = [['15,000+','Verified rental leads'],['800+','Societies mapped'],['95%','Lead response target'],['24 hrs','Verification SLA']];
  return <section className="metrics-strip"><div className="container metric-grid">{items.map(([n,l])=><div className="metric-card" key={l}><strong>{n}</strong><span>{l}</span></div>)}</div></section>
}

function SocietyCard({ s, setRoute }) { return <article className="society-card" onClick={()=>setRoute('society')}><img src={s.image}/><div className="society-overlay"><Badge>Verified</Badge></div><div><p><MapPin size={15}/> {s.locality}, {s.city}</p><h3>{s.name}</h3><div className="rent-row"><strong>{s.rent}</strong><span>{s.active} active rentals</span></div></div></article> }

function PropertyCard({ l, setRoute }) { return <article className="property-card"><div className="image-wrap"><img src={l.image}/><div className="overlay-badges">{l.featured&&<Badge tone="gold">Featured</Badge>}<Badge>Verified</Badge></div></div><div className="property-body"><h3>{l.society.name}</h3><p className="locality"><MapPin size={14}/> {l.society.locality}, {l.society.city}</p><div className="price"><strong>{l.rent}<small>/month</small></strong><span>{l.bhk}</span></div><p>{l.title}</p><div className="meta"><span>{l.area}</span><span>{l.furnishing}</span><span>{l.available}</span></div><Button variant="secondary" onClick={()=>setRoute('property')}>View Details</Button></div></article> }

function MiniChart() { return <div className="mini-chart">{[35,48,44,58,62,70,68,79,76,83,88,92].map((h,i)=><span key={i} style={{height:`${h}%`}} />)}</div> }
function IntelligenceBlock() { return <section className="section"><div className="container section-head"><div><Badge tone="gold">Rental intelligence</Badge><h2>Make rental decisions with market context</h2><p>Trend-led society pages help tenants compare demand, inventory and rent movement before enquiring.</p></div></div><div className="container intel-grid"><div className="intel-card large"><div><h3>Golf Course Road rent trend</h3><p>Sample 12-month movement for premium 3 BHK society rentals.</p></div><MiniChart/></div><div className="intel-card"><TrendingUp/><strong>High</strong><span>Demand score</span><div className="progress"><i style={{width:'92%'}} /></div></div><div className="intel-card"><Building2/><strong>214</strong><span>Premium rentals tracked</span><div className="progress"><i style={{width:'78%'}} /></div></div><div className="intel-card"><Clock3/><strong>12 days</strong><span>Avg. time to rent</span><div className="progress"><i style={{width:'66%'}} /></div></div></div></section> }

function LifestyleDiscovery({ setRoute }) {
  const items = [
    [Users,'Family friendly','Societies preferred by families with schools and parks nearby.'],
    [BriefcaseBusiness,'Near Cyber City','Premium homes with fast office access in Gurgaon.'],
    [Train,'Metro connected','Rentals near metro and key commute corridors.'],
    [PawPrint,'Pet friendly','Homes and societies with flexible pet policies.'],
    [Sparkles,'Luxury communities','High-end residences with clubhouse-led living.'],
    [Navigation,'Near tech parks','Whitefield, Bellandur and Outer Ring Road access.']
  ];
  return <section className="section sand"><div className="container section-head"><div><Badge>Discover by lifestyle</Badge><h2>Search the way people actually live</h2></div></div><div className="container lifestyle-grid">{items.map(([Icon,t,d])=><button className="lifestyle-card" key={t} onClick={()=>setRoute('search')}><Icon/><strong>{t}</strong><span>{d}</span></button>)}</div></section>
}

function HomePage({ setRoute }) { return <><Hero setRoute={setRoute}/><TrustMetrics/><section className="section featured-intro"><div className="container section-head"><div><Badge tone="gold">Society-first discovery</Badge><h2>Featured societies</h2><p>Every society becomes a rental marketplace with listings, trends, amenities and locality intelligence.</p></div><button onClick={()=>setRoute('search')}>View all <ArrowRight size={16}/></button></div><div className="container grid societies">{societies.map(s=><SocietyCard key={s.id} s={s} setRoute={setRoute}/>)}</div></section><LifestyleDiscovery setRoute={setRoute}/><section className="section"><div className="container section-head"><div><Badge>Verified rentals</Badge><h2>Latest visit-ready homes</h2></div></div><div className="container grid properties">{listings.slice(0,3).map(l=><PropertyCard key={l.id} l={l} setRoute={setRoute}/>)}</div></section><IntelligenceBlock/><section className="section cta"><div className="container cta-box"><div><h2>Own a flat in a premium society?</h2><p>List it with verification and reach serious tenants faster.</p></div><Button variant="premium" onClick={()=>setRoute('post')}>List Your Property</Button></div></section></> }

function SearchPage({ setRoute }) { const [city,setCity]=useState('All'); const filtered=useMemo(()=>city==='All'?listings:listings.filter(l=>l.society.city===city),[city]); return <main className="page"><div className="container"><div className="page-title"><Badge>Search</Badge><h1>{filtered.length} verified society rentals</h1><p>Society-first rental discovery for Gurgaon and Bangalore.</p></div><div className="search-layout"><aside className="filters"><h3><Filter size={18}/> Filters</h3><label>City<select value={city} onChange={e=>setCity(e.target.value)}><option>All</option><option>Gurgaon</option><option>Bangalore</option></select></label><label>BHK<select><option>Any</option><option>2 BHK</option><option>3 BHK</option><option>4 BHK</option></select></label><label>Budget<select><option>Any</option><option>Under ₹50k</option><option>₹50k–₹1L</option><option>₹1L+</option></select></label><label className="check"><input type="checkbox"/> Verified only</label><Button>Save Alert</Button></aside><section className="results">{filtered.map(l=><PropertyCard key={l.id} l={l} setRoute={setRoute}/>)}</section></div></div></main> }

function PropertyPage({ setRoute }) { const l=listings[0]; return <main className="page detail"><div className="container"><div className="gallery"><img src={l.image}/><img src={societies[1].image}/><img src={societies[2].image}/></div><div className="detail-grid"><section><Badge>Verified Property</Badge><h1>{l.society.name}</h1><p className="muted"><MapPin size={16}/> {l.society.locality}, {l.society.city}</p><div className="price hero-price"><strong>{l.rent}<small>/month</small></strong><span>{l.bhk}</span></div><h3>{l.title}</h3><div className="spec-grid">{[['Deposit',l.deposit],['Area',l.area],['Furnishing',l.furnishing],['Available',l.available],['Tenants',l.tenants],['Maintenance',l.maintenance]].map(([a,b])=><div key={a}><span>{a}</span><strong>{b}</strong></div>)}</div><h2>Why this home works</h2><ul className="ticks"><li>Verified society inventory</li><li>Visit-ready apartment</li><li>Premium family-oriented community</li><li>Strong access to business districts</li></ul><h2>Society context</h2><p>DLF Park Place is a high-demand residential society on Golf Course Road with premium amenities, strong security and consistent rental demand.</p></section><aside className="lead-card"><h3>Schedule a visit</h3><input placeholder="Your name"/><input placeholder="Phone number"/><textarea placeholder="I am interested in this property"/><Button><Phone size={16}/> Request Callback</Button><Button variant="secondary"><MessageCircle size={16}/> WhatsApp</Button></aside></div></div></main> }

function SocietyPage({ setRoute }) { const s=societies[0]; return <main><section className="society-hero"><div className="container"><img src={s.image}/><div><Badge tone="gold">Verified Society</Badge><h1>{s.name}</h1><p><MapPin size={17}/> {s.locality}, {s.city}</p><div className="hero-stats"><span>{s.rent} rent range</span><span>{s.active} active rentals</span><span>{s.demand}% demand score</span></div></div></div></section><section className="section sand"><div className="container society-detail-grid"><div><Badge tone="gold">Premium society rental intelligence</Badge><h2>Why people choose {s.name}</h2><p>High-demand gated residential society with verified rental inventory, strong family demand and premium amenities.</p><div className="why-grid">{['Rapid Metro access','Preferred by senior executives','24x7 power backup','Large central greens','Close to Cyber Hub','Premium maintenance standards'].map(x=><div key={x}><CheckCircle2 size={18}/>{x}</div>)}</div><div className="stats-grid compact">{[[s.avg2,'Avg 2BHK rent'],[s.avg3,'Avg 3BHK rent'],[s.active,'Active rentals'],['Family','Popular tenant type']].map(([a,b])=><div key={b}><strong>{a}</strong><span>{b}</span></div>)}</div><div className="intel-card large society-chart"><h3>12-month rent trend</h3><MiniChart/></div><h2>Available rentals</h2><div className="results inline"><PropertyCard l={listings[0]} setRoute={setRoute}/></div></div><aside className="amenity-box"><h3>Amenities</h3>{['Clubhouse','Gym','Pool','Power backup','Security','Kids play area','Parking','Landscaped greens'].map(a=><span key={a}><CheckCircle2 size={16}/> {a}</span>)}<h3>Nearby</h3>{['Cyber City','Rapid Metro','Top schools','Hospitals','Premium retail'].map(a=><span key={a}><MapPin size={16}/> {a}</span>)}</aside></div></section></main> }

function PostPropertyPage(){ return <main className="page"><div className="container narrow"><div className="page-title"><Badge tone="gold">Owner listing</Badge><h1>List your society flat</h1><p>Submit your rental. Admin verification workflow will approve it before publishing.</p></div><form className="form-card"><div className="two"><input placeholder="Owner name"/><input placeholder="Phone number"/></div><div className="two"><select><option>Gurgaon</option><option>Bangalore</option></select><input placeholder="Society name"/></div><div className="two"><select><option>2 BHK</option><option>3 BHK</option><option>4 BHK</option></select><input placeholder="Monthly rent"/></div><textarea placeholder="Property details"/><div className="upload"><Upload/>Upload images placeholder</div><Button>Submit for Verification</Button></form></div></main> }
function DashboardPage(){ return <div className="dashboard"><aside><h2>SocietyFlats</h2>{['Overview','Saved Properties','Visits','Alerts','Profile'].map(x=><button key={x}><LayoutDashboard size={16}/>{x}</button>)}</aside><section><h1>Tenant Dashboard</h1><div className="stats-grid">{[['4','Saved homes'],['2','Visits planned'],['3','Active alerts'],['12','Recommended societies']].map(([a,b])=><div key={b}><strong>{a}</strong><span>{b}</span></div>)}</div><div className="table"><h3>Recent activity</h3><p>Visit request sent for DLF Park Place</p><p>Search alert created for Whitefield 2 BHK</p></div></section></div> }
function AdminPage(){ return <div className="dashboard admin"><aside><h2>Admin</h2>{['Dashboard','Listings','Societies','Leads','Verification','Payments','SEO'].map(x=><button key={x}><BarChart3 size={16}/>{x}</button>)}</aside><section><h1>Admin Control Center</h1><div className="stats-grid">{[['38','New leads'],['14','Pending listings'],['7','Verification queue'],['₹2.4L','Monthly revenue sample']].map(([a,b])=><div key={b}><strong>{a}</strong><span>{b}</span></div>)}</div><div className="table"><h3>Lead pipeline</h3><p>New → Contacted → Visit Scheduled → Closed → Lost</p><p>Audit logs, role permissions and verification panels connect in backend phase.</p></div></section></div> }
function Footer(){ const col=(t,items)=><div><h4>{t}</h4>{items.map(i=><button key={i}>{i}</button>)}</div>; return <footer><div className="container footer-grid"><div><h2>SocietyFlats</h2><p>Verified society rentals for Gurgaon and Bangalore. Built society-first, trust-first and data-first.</p><p className="footer-brand-note">Premium rental discovery for serious tenants, owners and verified broker partners.</p></div>{col('Gurgaon',['Golf Course Road','DLF Phase 5','Sohna Road','Sector 56'])}{col('Bangalore',['Whitefield','HSR Layout','Bellandur','Sarjapur Road'])}{col('Popular societies',['DLF Park Place','M3M Golf Estate','Prestige Shantiniketan','Brigade Gateway'])}{col('Company',['About','Guides','Privacy','Terms','Contact'])}</div></footer> }

function App(){ const [route,setRoute]=useState('home'); if(route==='dashboard') return <DashboardPage/>; if(route==='admin') return <AdminPage/>; const pages={home:<HomePage setRoute={setRoute}/>,search:<SearchPage setRoute={setRoute}/>,property:<PropertyPage setRoute={setRoute}/>,society:<SocietyPage setRoute={setRoute}/>,post:<PostPropertyPage/>,trends:<HomePage setRoute={setRoute}/>,guides:<HomePage setRoute={setRoute}/>}; return <><Header route={route} setRoute={setRoute}/>{pages[route]||pages.home}<Footer/></> }

createRoot(document.getElementById('root')).render(<App />);
